# Docker file to run a container that will run the LuxAI S1 in Python 3
# (no GPU).

# Load NodeJS image for node 18.12.1.
FROM node:18.12.1-slim

# Set locale for variable (pulled from dockerfile in original OpenAI
# GPT2 repository).
ENV LANG=C.UTF-8

# Create a directory in the docker container. Set the working directory
# in the container to that newly created directory and then add all
# files from the current directory in the host to the working directory
# in the container.
RUN mkdir /run-LuxAI-S1
WORKDIR /run-LuxAI-S1
ADD . /run-LuxAI-S1

# Set up a volume so that the current directory in the host is
# connected to the working directory in the container.

# Install the required LuxAI Season 1 competition design.
RUN npm install -g @lux-ai/2021-challenge@latest

# Install Python 3 (v3.9 is used I believe).
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN python3 -m pip install --upgrade pip

# Install all required modules in the requirements.txt file.
RUN pip3 install -r requirementsS1.txt

# Run the LuxAI S1 game with the selected algorithms.
# CMD ["python3", "--version"]
# CMD ["lux-ai-2021", "Lux-Design-S1/simple/main.py", "Lux-Design-S1/simple/main.py", "--out=replay.json"]