# Docker file to run a container that will run the LuxAI S1 local
# replay viwer.

# Load NodeJS image for node 18.12.1.
FROM node:18.12.1-slim

# Set locale for variable (pulled from dockerfile in original OpenAI
# GPT2 repository).
ENV LANG=C.UTF-8

# Create a directory in the docker container. Set the working directory
# in the container to that newly created directory and then add all
# files from the current directory in the host to the working directory
# in the container.
RUN mkdir /run-LuxAI-S1-viewer
WORKDIR /run-LuxAI-S1-viewer
# ADD . /run-LuxAI-S1-viewer <- Do not use. The below ADD command adds only the Lux-Viewer-S1 (submodule) to the working directory (all we need)
ADD /Lux-Viewer-S1 /run-LuxAI-S1-viewer

# Set up a volume so that the current directory in the host is
# connected to the working directory in the container.

# Install the necessary npm package.
RUN npm i -g serve

# Expose port 5000 from the docker side.
EXPOSE 5000

# Run the Terminal game with the selected algorithms.
CMD ["npm", "run", "serve"]